
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Default values for esk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretRBAC:
  backend: false
  defaultAllow: false

backends:
  vault:
    enabled: false
    address: ""
    token_path: ""
    ca_cert: ""
    defaultMountPoint: kv

  aws:
    enabled: false
    accountID: ""
    region: ""
    oidcProvider:
    credentialsPath:
    crossplane:
      enabled: false
      injector:
        roleName:
        policyName:
      operator:
        roleName:
        policyName:
  
  gcp:
    enabled: false
    projectID: ""

init:
  image:
    repository: esk8s/esk-init
    pullPolicy: IfNotPresent
    tag: 0.8.0


injector:
  enabled: true

  replicaCount: 1

  labels: {}

  image:
    repository: esk8s/esk-injector
    pullPolicy: IfNotPresent
    tag: 0.8.0

  tls:
    # Path to the tls certificate, required if secretName is empty and certificateGenerator is disabled
    certPath:

    # Path to the tls key, required if secretName is empty and certificateGenerator is disabled
    keyPath:

    # Path to the ca bundle for the webhooks, required if certificateGenerator is disabled
    # TODO: currently this fails silently
    ca:
    secretName:

  rbac:
    create: true

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  matchPolicy: Equivalent
  failurePolicy: Ignore
  namespaceSelector: {}
  sideEffects: None
  timeoutSeconds: 10
  reinvocationPolicy: Never

  service:
    type: ClusterIP
    port: 443

  env: {}
  resources: {}
  autoscaling:
    enabled: false
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

certificateGenerator:
  enabled: true

  autoApproveCertificate: false
  image:
    repository: esk8s/esk-cert-gen
    pullPolicy: IfNotPresent
    tag: 1.0.0

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  labels: {}

operator:
  enabled: true

  replicaCount: 1

  image:
    repository: esk8s/esk-operator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.8.0

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  rbac:
    create: true

  plugins: []
  # ['gitlab_access_token', 'aws_access_key']

  labels: {}

  env: {}
  resources: {}
  autoscaling:
    enabled: false
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumeMounts: []

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

