{{- if .Values.injector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "injector.fullname" . }}
  labels:
    {{- include "injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.injector.service.type }}
  ports:
    - port: {{ .Values.injector.service.port }}
      targetPort: injector
      protocol: TCP
      name: injector
  selector:
    component.esk.io: injector
{{- end }}