{{- if .Values.backends.aws.crossplane.enabled }}
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: "{{ include "operator.fullname" . }}"
spec:
  forProvider:
    name: {{ .Values.backends.aws.crossplane.operator.policyName | default (include "operator.fullname" .) | quote }}
    description: Policy for the esk operator
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:*",
                "iam:CreateAccessKey",
                "iam:DeleteAccessKey"
            ],
            "Resource": "*"
          }
        ]
      }
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: {{ include "operator.fullname" . }}
  annotations:
    crossplane.io/external-name: {{ .Values.backends.aws.crossplane.operator.roleName | default (include "operator.fullname" .) }}
spec:
  forProvider:
    description: Role for the esk operator
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::{{ .Values.backends.aws.accountID }}:oidc-provider/oidc.eks.{{ .Values.backends.aws.region }}.amazonaws.com/id/{{ .Values.backends.aws.oidcProvider }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringLike": {
                "oidc.eks.{{ .Values.backends.aws.region }}.amazonaws.com/id/{{ .Values.backends.aws.oidcProvider }}:sub": "system:serviceaccount:{{ .Release.Namespace }}:{{ include "operator.serviceAccountName" . }}"
              }
            }
          }
        ]
      }
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "operator.fullname" . }}
spec:
  forProvider:
    policyArn: arn:aws:iam::{{ .Values.backends.aws.accountID }}:policy/{{ .Values.backends.aws.crossplane.operator.policyName | default (include "operator.fullname" .) }}
    roleName: {{ .Values.backends.aws.crossplane.operator.roleName | default (include "operator.fullname" .) }}
{{- end }}
